### ISSUE TITLE
Archiving GitHub codebase makes it unaccessible

### ISSUE THREAD

**Issue by soanvig** [sturdy-dev/sturdy#812]
Hello! I'm testing Sturdy. It looks interesting.

I encountered a critical problem. I'm using fresh Sturdy version (I cannot check version number, but the one available on getsturdy.com website from 15.03.2022). My platform is Windows.

1. I connected to GitHub
2. Connected to one repository and created a codebase for that
3. Because I selected wrong directory (**BTW I expected Sturdy to reuse directory that I had locally, but it created new directory with repository name inside selected one**) I archived my codebase
4. This repository cannot be converted into codebase anymore in any way. I get various errors (the first one is that this repository was archived, then 404 pages, empty pages and generally application is going wild: for example button "Create codebase" stops working until I restart Sturdy).

Removing Sturdy installation from GitHub and resetuping it again fixed the problem. However my created pull request was not "imported", and I don't how how to actually switch to it using Sturdy (it was imported the first time I tried Sturdy).

**Comment by zegl** [comment]
Hey Mateusz, and thanks for taking Sturdy for a spin. ❤️ 

This is a great bug report, I've been able to reproduce the issue where the repository can't be imported to a codebase again.  And the issue where pull requests where not imported the second time is related to the first issue.

I'll start working on a fix right away. 👍

**Comment by soanvig** [comment]
@zegl I see this is merged. Is it automatically deployed?

**Comment by zegl** [comment]
@soanvig Yes, it's deployed to Sturdy in the Cloud (but not yet included in any self-hosted release).

**Comment by soanvig** [comment]
Yeah, so this issue looks like resolved
