### ISSUE TITLE
Generic Linux install

### ISSUE THREAD

**Issue by soanvig** [sturdy-dev/sturdy#840]
Hello. I see only *.deb or *.rpm packages. I'm using Void Linux distro, therefore these package formats are beyond my range.

Is it possible to release build instructions (like requirements and so on) for custom Linux distribution or provide AppImage?  I just open this for discussion, because that's the issue that you will want to cover sooner or later.

**Comment by ngalaiko** [comment]
Hi @soanvig! 

Look like electron-builder that we use to build the app is able to produce AppImage artifacts, which is good news. I'll test it today and see if it actually works

**Comment by ngalaiko** [comment]
Hi again @soanvig 

Here are .AppImage builds for [amd64](https://autoupdate.getsturdy.com/client/linux/amd64/Sturdy.AppImage) and [arm64](https://autoupdate.getsturdy.com/client/linux/arm64/Sturdy.AppImage). Let me know if you face any issues running it. 

Plus, I would appriciate help if you know how to set a desktop icon for those 🤔 I am not a daily linux user and there is [some confision around the subject ](https://github.com/AppImage/AppImageKit/issues/346)

**Comment by soanvig** [comment]
Thanks. I don't know desktop icons system, and app image very well neither 😓

**Comment by soanvig** [comment]
Yeah, this build works for me as well :-)
