### ISSUE TITLE
How to "undo"

### ISSUE THREAD

**Issue by soanvig** [sturdy-dev/sturdy#922]
I commited one pack of changes, pushed to PR.

Now I made few changes in the same PR, but I would like to undo them, because they were draft.

Normally in Git I would use `git reset --hard HEAD` or something, but my codebase is not a "repository", and in Sturdy I see `undo` button, but it shows all changes made in the PR, not the latest pack of them.

So how can I actually undo latest working tree changes?

**Comment by ngalaiko** [comment]
Hi,

In your Draft (previously known as workspace), you can select one or more file diff hunks and hit `Undo` to remove them from the diff. It will also undo them on your machine.

If you want to remove a change that is already merged into the codebase, you can create a new Draft change with a `Revert` button from the change page

**Comment by soanvig** [comment]
Ok, but in draft changelog I see all changes made to the draft, while i want to undo only changes that are in git working tree (this is: not commited)

**Comment by ngalaiko** [comment]
Would you mind sending some screenshots @soanvig ? Maybe I don't understand extcly what you mean by draft changelog and git working tree in this context

**Comment by soanvig** [comment]
1. Make some changes
2. Update PR
3. Make some changes

Now I want to revert changes that I made in step 3, but Sturdy changelog shows changes from 1 and 3.

**Comment by ngalaiko** [comment]
@soanvig I guess what you want is to select changes on Sturdy that you want to undo and click "Undo"

Then, you click "Update Pull Request" button to force push Sturdy Draft change diffs to GitHub Pull Request

We do not automatically send all the updates to GitHub, it's too much data to send

**Comment by soanvig** [comment]
Yeah, but i see changes from previous commit as well, therefore I cannot select just recent changes.

**Comment by ngalaiko** [comment]
If you use study <-> github integration, Sturdy force pushes a single commit to the github pr, which is the same as diffs in sturdy draft change. So I don't quite get what do you mean by "previous" commit here 🤔 

Do you modify your github PR from both sturdy and git maybe, and that leads to the confusion?

**Comment by ngalaiko** [comment]
OK, I see. The minimumal bit you can undo is a Hunk - which is a part of a File Diff, for example:

<img width="1283" alt="Screenshot 2022-03-31 at 08 29 29" src="https://user-images.githubusercontent.com/15010292/160990629-0e841798-e395-4d30-b793-a244e167b562.png">
<img width="921" alt="Screenshot 2022-03-31 at 08 26 12" src="https://user-images.githubusercontent.com/15010292/160990185-4a23e513-34a8-413f-84a3-29e4aae3a5df.png">

There is no way now to undo "last push to github pr", because we treat github pr as a full copy of a draft, where draft is the source of truth.

**Comment by soanvig** [comment]
> There is no way now to undo "last push to github pr", because we treat github pr as a full copy of a draft, where draft is the source of truth.

I don't want to undo push to GitHub PR. Quite the opposite. I want to undo recent changes, that weren't published yet.

Well, anyway it seems to be impossible. Which in my opinion completely kills the whole Sturdy project at this moment. So to me Git is so powerful, I can do very interesting things, and Sturdy is nice, but at the same time it completely takes away all git power from me, because the directory (with the code Sturdy is working on) is not git repository at all.
